-- Configura il colore di sfondo per nvim-navic
vim.api.nvim_set_hl(0, "WinBar", {fg = "#ffffff", bg = "#272f35"})
vim.api.nvim_set_hl(0, "WinBarNC", {fg = "#ffffff", bg = "#272f35"})
vim.api.nvim_set_hl(0, "NavbuddyCursor", {fg = "#131a21", bg = "#ced4df"})
vim.api.nvim_set_hl(0, "NavicIconsFile", { default = true, bg = "#272f35", fg = "#eceff4" })
vim.api.nvim_set_hl(0, "NavicIconsModule", { default = true, bg = "#272f35", fg = "#bf616a" })
vim.api.nvim_set_hl(0, "NavicIconsNamespace", { default = true, bg = "#272f35", fg = "#d08770" })
vim.api.nvim_set_hl(0, "NavicIconsPackage", { default = true, bg = "#272f35", fg = "#ebcb8b" })
vim.api.nvim_set_hl(0, "NavicIconsClass", { default = true, bg = "#272f35", fg = "#a3be8c" })
vim.api.nvim_set_hl(0, "NavicIconsMethod", { default = true, bg = "#272f35", fg = "#88c0d0" })
vim.api.nvim_set_hl(0, "NavicIconsProperty", { default = true, bg = "#272f35", fg = "#b48ead" })
vim.api.nvim_set_hl(0, "NavicIconsField", { default = true, bg = "#272f35", fg = "#8fbcbb" })
vim.api.nvim_set_hl(0, "NavicIconsConstructor", { default = true, bg = "#272f35", fg = "#d8dee9" })
vim.api.nvim_set_hl(0, "NavicIconsEnum", { default = true, bg = "#272f35", fg = "#bf616a" })
vim.api.nvim_set_hl(0, "NavicIconsInterface", { default = true, bg = "#272f35", fg = "#d08770" })
vim.api.nvim_set_hl(0, "NavicIconsFunction", { default = true, bg = "#272f35", fg = "#ebcb8b" })
vim.api.nvim_set_hl(0, "NavicIconsVariable", { default = true, bg = "#272f35", fg = "#a3be8c" })
vim.api.nvim_set_hl(0, "NavicIconsConstant", { default = true, bg = "#272f35", fg = "#88c0d0" })
vim.api.nvim_set_hl(0, "NavicIconsString", { default = true, bg = "#272f35", fg = "#b48ead" })
vim.api.nvim_set_hl(0, "NavicIconsNumber", { default = true, bg = "#272f35", fg = "#8fbcbb" })
vim.api.nvim_set_hl(0, "NavicIconsBoolean", { default = true, bg = "#272f35", fg = "#d8dee9" })
vim.api.nvim_set_hl(0, "NavicIconsArray", { default = true, bg = "#272f35", fg = "#bf616a" })
vim.api.nvim_set_hl(0, "NavicIconsObject", { default = true, bg = "#272f35", fg = "#d08770" })
vim.api.nvim_set_hl(0, "NavicIconsKey", { default = true, bg = "#272f35", fg = "#ebcb8b" })
vim.api.nvim_set_hl(0, "NavicIconsNull", { default = true, bg = "#272f35", fg = "#a3be8c" })
vim.api.nvim_set_hl(0, "NavicIconsEnumMember", { default = true, bg = "#272f35", fg = "#88c0d0" })
vim.api.nvim_set_hl(0, "NavicIconsStruct", { default = true, bg = "#272f35", fg = "#b48ead" })
vim.api.nvim_set_hl(0, "NavicIconsEvent", { default = true, bg = "#272f35", fg = "#8fbcbb" })
vim.api.nvim_set_hl(0, "NavicIconsOperator", { default = true, bg = "#272f35", fg = "#d8dee9" })
vim.api.nvim_set_hl(0, "NavicIconsTypeParameter", { default = true, bg = "#272f35", fg = "#bf616a" })
vim.api.nvim_set_hl(0, "NavicText", { default = true, bg = "#272f35", fg = "#eceff4" })
vim.api.nvim_set_hl(0, "NavicSeparator", { default = true, bg = "#272f35", fg = "#88c0d0" })
